spring.application.name=secure-sms

# Server Configuration
server.port=${PORT:8080}

# Database Configuration (H2 In-Memory)
#spring.datasource.url=jdbc:h2:mem:schoolsystem
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# Disable the automatic in-memory mode
# spring.datasource.url=jdbc:h2:mem:schoolsystem

# Use a local file (e.g., 'school-db.mv.db' in your project folder)
#spring.datasource.url=jdbc:h2:file:C:/Documents/important/school-db
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Hibernate settings
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update

# Database Configuration (MySQL)
# Cloud database configuration, use enevironment variables, fall back to local
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/schoolsystem?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.MySQLDialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Security (Temporary for Dev)
#spring.security.user.name=admin
#spring.security.user.password=admin

#DEBUGGING
#logging.level.root=DEBUG
#logging.level.org.springframework=DEBUG
#server.ssl.enabled=false
# This effectively tells Tomcat to use standard Java I/O instead of looking for the native APR library
#logging.level.org.springframework.security=TRACE